<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nuplane.Runtime\Nuplane.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Store\Nuplane.Store.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.NuGet\Nuplane.NuGet.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
  </ItemGroup>

</Project>

