<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nuplane.PackageStore.TestHost\Nuplane.PackageStore.TestHost.csproj"
                      ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="..\..\src\Nuplane.Admin\Nuplane.Admin.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Admin.Api\Nuplane.Admin.Api.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Api\Nuplane.Loading.Api.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
  </ItemGroup>

  <Target Name="CopyPackageStoreTestHost" AfterTargets="Build">
    <ItemGroup>
      <PackageStoreTestHostArtifact Include="$(MSBuildThisFileDirectory)..\Nuplane.PackageStore.TestHost\bin\$(Configuration)\net10.0\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(PackageStoreTestHostArtifact)"
          DestinationFiles="@(PackageStoreTestHostArtifact->'$(OutDir)PackageStoreTestHost\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
