<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nuplane.Admin\Nuplane.Admin.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Admin.Api\Nuplane.Admin.Api.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Api\Nuplane.Loading.Api.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
  </ItemGroup>

</Project>

