<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <ProjectReference Include="..\Nuplane.Runtime\Nuplane.Runtime.csproj" />
    <ProjectReference Include="..\Nuplane.Store\Nuplane.Store.csproj" />
    <ProjectReference Include="..\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
    <ProjectReference Include="..\Nuplane.Abstractions\Nuplane.Abstractions.csproj" />
  </ItemGroup>

</Project>

