<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Nuplane</Title>
    <Description>Primary DI and configuration entrypoint for Nuplane runtime services in .NET applications.</Description>
    <PackageTags>$(NuplanePackageTags);dependency-injection;configuration;hosting;runtime</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nuplane.Runtime.Tests" />
    <InternalsVisibleTo Include="Nuplane.Admin" />
    <InternalsVisibleTo Include="Nuplane.Sources.Directory.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <ProjectReference Include="..\Nuplane.Runtime\Nuplane.Runtime.csproj" />
    <ProjectReference Include="..\Nuplane.NuGet\Nuplane.NuGet.csproj" />
    <ProjectReference Include="..\Nuplane.Store\Nuplane.Store.csproj" />
    <ProjectReference Include="..\Nuplane.Abstractions\Nuplane.Abstractions.csproj" />
  </ItemGroup>

</Project>
