<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Nuplane.Runtime\Nuplane.Runtime.csproj" />
    <ProjectReference Include="..\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\Nuplane.Loading.Abstractions\Nuplane.Loading.Abstractions.csproj" />
  </ItemGroup>
</Project>
