<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Nuplane.Loading.Tests" />
    <InternalsVisibleTo Include="Nuplane.Integration.Tests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nuplane\Nuplane.csproj" />
    <ProjectReference Include="..\Nuplane.Runtime\Nuplane.Runtime.csproj" />
    <ProjectReference Include="..\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\Nuplane.Loading.Abstractions\Nuplane.Loading.Abstractions.csproj" />
  </ItemGroup>
</Project>
