<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nuplane.Abstractions\Nuplane.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Admin.Api\Nuplane.Admin.Api.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Api\Nuplane.Loading.Api.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
    <ProjectReference Include="..\..\src\Nuplane\Nuplane.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Abstractions\Nuplane.Loading.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\Nuplane.Sample.Abstractions\Nuplane.Sample.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
