<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Nuplane.Loading.Tests.Fixtures</AssemblyName>
    <RootNamespace>Nuplane.Loading.Tests.Fixtures.Conflict</RootNamespace>
    <Version>2.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>

</Project>
