<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <ProjectReference Include="..\..\src\Nuplane.Runtime\Nuplane.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Nuplane\Nuplane.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Admin\Nuplane.Admin.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Hosting\Nuplane.Loading.Hosting.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Sources.Directory.Hosting\Nuplane.Sources.Directory.Hosting.csproj" />
  </ItemGroup>

</Project>
