<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Plugin.Root</AssemblyName>
    <RootNamespace>Plugin.Root</RootNamespace>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="coverlet.collector" />
    <PackageReference Remove="Microsoft.NET.Test.Sdk" />
    <PackageReference Remove="xunit" />
    <PackageReference Remove="xunit.runner.visualstudio" />
    <Using Remove="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nuplane.Loading.Tests.Fixtures.Dependency\Nuplane.Loading.Tests.Fixtures.Dependency.csproj" />
  </ItemGroup>

</Project>
