<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <ProjectReference Include="..\Nuplane.Abstractions\Nuplane.Abstractions.csproj" />
    <ProjectReference Include="..\Nuplane.Store\Nuplane.Store.csproj" />
    <ProjectReference Include="..\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
    <ProjectReference Include="..\Nuplane.Loading.Abstractions\Nuplane.Loading.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nuplane.Runtime.Tests" />
  </ItemGroup>

</Project>
