<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nuplane.Abstractions\Nuplane.Abstractions.csproj" />
    <ProjectReference Include="..\Nuplane.Store\Nuplane.Store.csproj" />
    <ProjectReference Include="..\Nuplane.NuGet\Nuplane.NuGet.csproj" />
    <ProjectReference Include="..\Nuplane.Sources.Directory\Nuplane.Sources.Directory.csproj" />
    <ProjectReference Include="..\Nuplane.Loading\Nuplane.Loading.csproj" />
  </ItemGroup>

</Project>


