<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Nuplane.Loading\Nuplane.Loading.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Abstractions\Nuplane.Loading.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Nuplane.Loading.Api\Nuplane.Loading.Api.csproj" />
    <ProjectReference Include="..\Nuplane.Loading.Tests.Fixtures\Nuplane.Loading.Tests.Fixtures.csproj" />
    <ProjectReference Include="..\Nuplane.Loading.Tests.Fixtures.BrokenCandidate\Nuplane.Loading.Tests.Fixtures.BrokenCandidate.csproj"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

</Project>
